 SELECT PL."Zone" AS PICKUP_ZONE,
    DL."Zone" AS DROPOFF_ZONE,
    TIP_AMOUNT
FROM TRIPS
INNER JOIN LOCATIONS AS PL ON "PULocationID" = PL."LocationID"
INNER JOIN LOCATIONS AS DL ON "DOLocationID" = DL."LocationID"
WHERE LPEP_PICKUP_DATETIME >= '2019-09-01'
    AND LPEP_PICKUP_DATETIME < '2019-10-01'
    AND PL."Zone" = 'Astoria'
ORDER BY TIP_AMOUNT DESC
LIMIT 1 ;
