 SELECT "Borough",
    SUM(TOTAL_AMOUNT) AS SUM_AMOUNT
FROM TRIPS
INNER JOIN LOCATIONS ON "PULocationID" = "LocationID"
WHERE LPEP_PICKUP_DATETIME >= '2019-09-18'
    AND LPEP_PICKUP_DATETIME < '2019-09-19'
GROUP BY "Borough"
ORDER BY SUM_AMOUNT DESC
LIMIT 3;
