SELECT LPEP_PICKUP_DATETIME,
    TRIP_DISTANCE
FROM
    (SELECT LPEP_PICKUP_DATETIME,
            TRIP_DISTANCE,
            RANK() OVER(
            ORDER BY TRIP_DISTANCE DESC) AS DIST_RANK
            FROM TRIPS)
WHERE DIST_RANK = 1;
